=== AhmmedSamier/xml-lab2/library.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT library (location,description,librarian,books)>
<!ELEMENT books (book*)>
<!ELEMENT book (title,ISBN,author,preface,parts)>
<!ELEMENT parts (part+)>
<!ELEMENT part (chapter+)>
<!ELEMENT chapter (summary,sections)>
<!ELEMENT sections (section+)>
<!ELEMENT section (p+)>

<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT preface (#PCDATA)>

<!ELEMENT summary (#PCDATA)>
<!ELEMENT p (#PCDATA)>

<!ATTLIST part title CDATA #REQUIRED>
<!ATTLIST chapter title CDATA #REQUIRED>

=== AhmmedSamier/xml-lab2/library - Copy.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <location>location</location>
    <description>desc</description>
    <librarian>ahmed</librarian>
    <books>
        <book>
            <title>book1</title>
            <ISBN>123</ISBN>
            <author>ahmed</author>
            <preface>abcd</preface>
            <parts>
                <part title="book1">
                    <chapter title="ch1">
                        <summary>abc</summary>
                        <sections>
                            <section>
                                <p>a</p>
                            </section>
                            <section>
								<p>b</p>
                            </section>
                            <section>
								<p>c</p>                            
                            </section>
                        </sections>
                    </chapter>
                </part>
            </parts>
        </book>
    </books>
</library>

=== AhmmedSamier/xml-lab2/library.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <location></location>
    <description></description>
    <librarian></librarian>
    <books>
        <book>
            <title></title>
            <ISBN></ISBN>
            <author></author>
            <preface></preface>
            <parts>
                <part title="">
                    <chapter title="">
                        <summary></summary>
                        <sections>
                            <section>
                                <p></p>
                            </section>
                            <section>
								<p></p>
                            </section>
                            <section>
								<p></p>                            
                            </section>
                        </sections>
                    </chapter>
                </part>
            </parts>
        </book>
    </books>
</library>
